'use server';
/**
 * @fileOverview A flow to improve AI-generated answers based on user feedback.
 *
 * - improveAnswerBasedOnFeedback - A function that handles the process of improving answers based on feedback.
 * - ImproveAnswerBasedOnFeedbackInput - The input type for the improveAnswerBasedOnFeedback function.
 * - ImproveAnswerBasedOnFeedbackOutput - The return type for the improveAnswerBasedOnFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveAnswerBasedOnFeedbackInputSchema = z.object({
  question: z.string().describe('The original question asked by the user.'),
  originalAnswer: z.string().describe('The original answer generated by the AI.'),
  feedback: z.string().describe('The user feedback on the answer.'),
});
export type ImproveAnswerBasedOnFeedbackInput = z.infer<
  typeof ImproveAnswerBasedOnFeedbackInputSchema
>;

const ImproveAnswerBasedOnFeedbackOutputSchema = z.object({
  improvedAnswer: z.string().describe('The improved answer based on the feedback.'),
});
export type ImproveAnswerBasedOnFeedbackOutput = z.infer<
  typeof ImproveAnswerBasedOnFeedbackOutputSchema
>;

export async function improveAnswerBasedOnFeedback(
  input: ImproveAnswerBasedOnFeedbackInput
): Promise<ImproveAnswerBasedOnFeedbackOutput> {
  return improveAnswerBasedOnFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveAnswerBasedOnFeedbackPrompt',
  input: {schema: ImproveAnswerBasedOnFeedbackInputSchema},
  output: {schema: ImproveAnswerBasedOnFeedbackOutputSchema},
  prompt: `You are an AI expert in improving answers based on user feedback.

  Original Question: {{{question}}}
  Original Answer: {{{originalAnswer}}}
  Feedback: {{{feedback}}}

  Based on the user feedback, improve the original answer to be more accurate and helpful. Return only the improved answer. Do not repeat the question or feedback in your answer.
  Improved Answer:`,
});

const improveAnswerBasedOnFeedbackFlow = ai.defineFlow(
  {
    name: 'improveAnswerBasedOnFeedbackFlow',
    inputSchema: ImproveAnswerBasedOnFeedbackInputSchema,
    outputSchema: ImproveAnswerBasedOnFeedbackOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
